// Code generated by protoc-gen-go-poseidon. DO NOT EDIT.
// versions:
// - protoc-gen-go-poseidon v0.1.0-dev
// - protoc                 (unknown)
// source: helloworld/helloworld.proto

package poseidon

import (
	context "context"
	pgrpc "github.com/lodgvideon/protoc-gen-go-poseidon/pgrpc"
	protocodec "github.com/lodgvideon/protoc-gen-go-poseidon/pgrpc/protocodec"
	helloworld "github.com/lodgvideon/protoc-gen-go-poseidon/testdata/helloworld"
)

// This is a compile-time assertion that this generated file is compatible
// with the pgrpc runtime it is being compiled against.
const _ = pgrpc.SupportPackageIsVersion1

const (
	Greeter_SayHello_FullMethodName        = "/helloworld.Greeter/SayHello"
	Greeter_LotsOfReplies_FullMethodName   = "/helloworld.Greeter/LotsOfReplies"
	Greeter_LotsOfGreetings_FullMethodName = "/helloworld.Greeter/LotsOfGreetings"
	Greeter_BidiHello_FullMethodName       = "/helloworld.Greeter/BidiHello"
)

// Greeter_LotsOfRepliesClient names the stream Greeter.LotsOfReplies returns.
//
// It is a POINTER alias. The stream carries a mutex and three atomics and
// must never be copied; a value alias would let `var s Greeter_LotsOfRepliesClient` compile
// and would turn passing one by value into a go vet copylocks finding in
// your build, not ours.
type Greeter_LotsOfRepliesClient = *pgrpc.ServerStream[helloworld.HelloReply]

// Greeter_LotsOfGreetingsClient names the stream Greeter.LotsOfGreetings returns.
//
// It is a POINTER alias. The stream carries a mutex and three atomics and
// must never be copied; a value alias would let `var s Greeter_LotsOfGreetingsClient` compile
// and would turn passing one by value into a go vet copylocks finding in
// your build, not ours.
type Greeter_LotsOfGreetingsClient = *pgrpc.ClientStream[helloworld.HelloRequest, helloworld.HelloReply]

// Greeter_BidiHelloClient names the stream Greeter.BidiHello returns.
//
// It is a POINTER alias. The stream carries a mutex and three atomics and
// must never be copied; a value alias would let `var s Greeter_BidiHelloClient` compile
// and would turn passing one by value into a go vet copylocks finding in
// your build, not ours.
type Greeter_BidiHelloClient = *pgrpc.BidiStream[helloworld.HelloRequest, helloworld.HelloReply]

// GreeterClient is the ergonomic face of the Greeter service.
// It allocates a response message per call.
// For the buffer-reusing path see GreeterCaller.
//
// Greeter is the canonical four-shape service.
type GreeterClient interface {
	// SayHello is the unary shape: one request, one reply.
	SayHello(ctx context.Context, in *helloworld.HelloRequest, opts ...pgrpc.CallOption) (*helloworld.HelloReply, error)
	// LotsOfReplies is the server-streaming shape: one request, a stream of
	// replies.
	LotsOfReplies(ctx context.Context, in *helloworld.HelloRequest, opts ...pgrpc.CallOption) (*pgrpc.ServerStream[helloworld.HelloReply], error)
	// LotsOfGreetings is the client-streaming shape: a stream of requests, one
	// reply.
	LotsOfGreetings(ctx context.Context, opts ...pgrpc.CallOption) (*pgrpc.ClientStream[helloworld.HelloRequest, helloworld.HelloReply], error)
	// BidiHello is the bidirectional shape: a stream each way, independently
	// driven.
	BidiHello(ctx context.Context, opts ...pgrpc.CallOption) (*pgrpc.BidiStream[helloworld.HelloRequest, helloworld.HelloReply], error)
}

type greeterClient struct {
	c *pgrpc.Client
}

var _ GreeterClient = (*greeterClient)(nil)

// NewGreeterClient returns the ergonomic face of Greeter over c.
func NewGreeterClient(c *pgrpc.Client) GreeterClient {
	return &greeterClient{c: c}
}

// NewGreeterClientOn builds a pgrpc.Client over cc with the protobuf codec and
// returns the ergonomic face of Greeter.
//
// The default codec is applied BEFORE opts, so a caller-supplied
// pgrpc.WithCodec still wins. It exists because pgrpc.NewClient panics without
// a codec and this package cannot supply one: the runtime must not import
// protobuf, while this generated file already does.
func NewGreeterClientOn(cc pgrpc.Invoker, opts ...pgrpc.ClientOption) GreeterClient {
	return NewGreeterClient(pgrpc.NewClient(cc,
		append([]pgrpc.ClientOption{pgrpc.WithCodec(protocodec.Codec{})}, opts...)...))
}

// SayHello is the unary shape: one request, one reply.
func (x *greeterClient) SayHello(ctx context.Context, in *helloworld.HelloRequest, opts ...pgrpc.CallOption) (*helloworld.HelloReply, error) {
	out := new(helloworld.HelloReply)
	if err := pgrpc.UnaryOpts(ctx, x.c, Greeter_SayHello_FullMethodName, in, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

// LotsOfReplies is the server-streaming shape: one request, a stream of
// replies.
func (x *greeterClient) LotsOfReplies(ctx context.Context, in *helloworld.HelloRequest, opts ...pgrpc.CallOption) (*pgrpc.ServerStream[helloworld.HelloReply], error) {
	return pgrpc.NewServerStreamOpts[helloworld.HelloReply](ctx, x.c, Greeter_LotsOfReplies_FullMethodName, in, opts...)
}

// LotsOfGreetings is the client-streaming shape: a stream of requests, one
// reply.
func (x *greeterClient) LotsOfGreetings(ctx context.Context, opts ...pgrpc.CallOption) (*pgrpc.ClientStream[helloworld.HelloRequest, helloworld.HelloReply], error) {
	return pgrpc.NewClientStreamOpts[helloworld.HelloRequest, helloworld.HelloReply](ctx, x.c, Greeter_LotsOfGreetings_FullMethodName, opts...)
}

// BidiHello is the bidirectional shape: a stream each way, independently
// driven.
func (x *greeterClient) BidiHello(ctx context.Context, opts ...pgrpc.CallOption) (*pgrpc.BidiStream[helloworld.HelloRequest, helloworld.HelloReply], error) {
	return pgrpc.NewBidiStreamOpts[helloworld.HelloRequest, helloworld.HelloReply](ctx, x.c, Greeter_BidiHello_FullMethodName, opts...)
}

// GreeterCaller is the buffer-reusing face of the Greeter service.
//
// One Caller serves ONE goroutine and ONE in-flight RPC. It owns the request
// marshal scratch, the response scratch and the resolved call configuration.
// The intended shape for a load generator is one Caller per virtual user,
// built once outside the request loop.
//
// A UNARY call allocates nothing in this layer. A STREAMING call allocates the
// stream and grows its send buffer once, so the Caller saves one resolved
// configuration per STREAM — not per message.
//
// CONFIG LIFETIME. Config is mutable and a call reads it SYNCHRONOUSLY, because
// poseidon walks the metadata inside NewStream. Mutate it outside the request
// loop only, never while a call or an open stream is using it.
//
// A concurrent second call fails with pgrpc.ErrCallerInUse rather than
// corrupting a request body.
//
// Greeter is the canonical four-shape service.
type GreeterCaller struct {
	pgrpc.Guard
	c       *pgrpc.Client
	cfg     pgrpc.CallConfig
	buf     []byte
	respBuf []byte
}

// NewGreeterCaller returns the buffer-reusing face of Greeter over c.
func NewGreeterCaller(c *pgrpc.Client) *GreeterCaller {
	return &GreeterCaller{c: c}
}

// NewGreeterCallerOn builds a pgrpc.Client over cc with the protobuf codec and
// returns the buffer-reusing face of Greeter. The default codec is applied
// BEFORE opts, so a caller-supplied pgrpc.WithCodec still wins.
func NewGreeterCallerOn(cc pgrpc.Invoker, opts ...pgrpc.ClientOption) *GreeterCaller {
	return NewGreeterCaller(pgrpc.NewClient(cc,
		append([]pgrpc.ClientOption{pgrpc.WithCodec(protocodec.Codec{})}, opts...)...))
}

// Config returns the mutable per-call configuration. Set it once, outside the
// request loop. Prefer Config().Apply(opts...) over assigning fields, so that
// option logic — metadata ownership above all — is not bypassed.
func (x *GreeterCaller) Config() *pgrpc.CallConfig { return &x.cfg }

// SayHello is the unary shape: one request, one reply.
func (x *GreeterCaller) SayHello(ctx context.Context, in *helloworld.HelloRequest, out *helloworld.HelloReply) error {
	if err := x.Enter(); err != nil {
		return err
	}
	defer x.Leave()
	return pgrpc.Unary(ctx, x.c, &x.cfg, Greeter_SayHello_FullMethodName, in, out, &x.buf, &x.respBuf)
}

// LotsOfReplies is the server-streaming shape: one request, a stream of
// replies.
func (x *GreeterCaller) LotsOfReplies(ctx context.Context, in *helloworld.HelloRequest) (*pgrpc.ServerStream[helloworld.HelloReply], error) {
	if err := x.Enter(); err != nil {
		return nil, err
	}
	defer x.Leave()
	return pgrpc.NewServerStream[helloworld.HelloReply](ctx, x.c.Invoker(), x.c.CodecFor(&x.cfg), &x.cfg, Greeter_LotsOfReplies_FullMethodName, in, &x.buf)
}

// LotsOfGreetings is the client-streaming shape: a stream of requests, one
// reply.
func (x *GreeterCaller) LotsOfGreetings(ctx context.Context) (*pgrpc.ClientStream[helloworld.HelloRequest, helloworld.HelloReply], error) {
	if err := x.Enter(); err != nil {
		return nil, err
	}
	defer x.Leave()
	return pgrpc.NewClientStream[helloworld.HelloRequest, helloworld.HelloReply](ctx, x.c.Invoker(), x.c.CodecFor(&x.cfg), &x.cfg, Greeter_LotsOfGreetings_FullMethodName, 0)
}

// BidiHello is the bidirectional shape: a stream each way, independently
// driven.
func (x *GreeterCaller) BidiHello(ctx context.Context) (*pgrpc.BidiStream[helloworld.HelloRequest, helloworld.HelloReply], error) {
	if err := x.Enter(); err != nil {
		return nil, err
	}
	defer x.Leave()
	return pgrpc.NewBidiStream[helloworld.HelloRequest, helloworld.HelloReply](ctx, x.c.Invoker(), x.c.CodecFor(&x.cfg), &x.cfg, Greeter_BidiHello_FullMethodName, 0)
}
