// Package e2e drives the generated client against a real grpc-go server over a
// real socket.
//
// Everything above this ran against fakes, which can only prove what the client
// TELLS a caller. Nothing until now has put a byte on a wire, and the streaming
// shapes in particular have never met an implementation that did not share
// their assumptions. grpc-go is that implementation.
package e2e

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"testing"
	"time"

	grpcgo "google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"

	"github.com/lodgvideon/poseidon-http-client/conn"
	poseidongrpc "github.com/lodgvideon/poseidon-http-client/grpc"
	"github.com/lodgvideon/protoc-gen-go-poseidon/pgrpc"
	"github.com/lodgvideon/protoc-gen-go-poseidon/pgrpc/protocodec"
	"github.com/lodgvideon/protoc-gen-go-poseidon/testdata/helloworld"
	"github.com/lodgvideon/protoc-gen-go-poseidon/testdata/helloworld/poseidon"
)

// greeter is the server behaviour under test. Each field lets one test bend one
// method without a second server type.
type greeter struct {
	// unaryErr, when set, is returned by SayHello instead of a reply. A
	// status.Error here becomes a Trailers-Only response — which, in poseidon's
	// own words, is how gRPC servers report most errors.
	unaryErr error
	// unaryHeader, when set, is sent as response metadata before the reply,
	// which stops the Trailers-Only shape from being the only one covered.
	unaryHeader metadata.MD
	// replies is how many messages LotsOfReplies sends.
	replies int
	// echoDelay is inserted before each streamed reply, so a test can close a
	// stream while the server is still producing.
	echoDelay time.Duration
}

func (g *greeter) sayHello(ctx context.Context, in *helloworld.HelloRequest) (*helloworld.HelloReply, error) {
	if len(g.unaryHeader) > 0 {
		if err := grpcgo.SendHeader(ctx, g.unaryHeader); err != nil {
			return nil, err
		}
	}
	if g.unaryErr != nil {
		return nil, g.unaryErr
	}
	// The reply echoes any x-tenant the client attached, so a metadata test can
	// assert what the SERVER saw rather than what the client believes it sent.
	reply := "hello " + in.GetName()
	if md, ok := metadata.FromIncomingContext(ctx); ok {
		if v := md.Get("x-tenant"); len(v) > 0 {
			reply += " [tenant=" + v[0] + "]"
		}
	}
	return &helloworld.HelloReply{Message: reply}, nil
}

func (g *greeter) lotsOfReplies(in *helloworld.HelloRequest, stream grpcgo.ServerStream) error {
	n := g.replies
	if n == 0 {
		n = 3
	}
	for i := range n {
		if g.echoDelay > 0 {
			time.Sleep(g.echoDelay)
		}
		msg := &helloworld.HelloReply{Message: fmt.Sprintf("%s #%d", in.GetName(), i)}
		if err := stream.SendMsg(msg); err != nil {
			return err
		}
	}
	return nil
}

func (g *greeter) lotsOfGreetings(stream grpcgo.ServerStream) error {
	var names []string
	for {
		var in helloworld.HelloRequest
		err := stream.RecvMsg(&in)
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return err
		}
		names = append(names, in.GetName())
	}
	return stream.SendMsg(&helloworld.HelloReply{
		Message: fmt.Sprintf("greeted %d: %v", len(names), names),
	})
}

func (g *greeter) bidiHello(stream grpcgo.ServerStream) error {
	for {
		var in helloworld.HelloRequest
		err := stream.RecvMsg(&in)
		if errors.Is(err, io.EOF) {
			return nil
		}
		if err != nil {
			return err
		}
		if err := stream.SendMsg(&helloworld.HelloReply{Message: "re: " + in.GetName()}); err != nil {
			return err
		}
	}
}

// greeterDesc is written by hand rather than generated by protoc-gen-go-grpc.
//
// It is 60 lines, it removes a code-generation step from the test toolchain,
// and — the actual reason — it puts the SERVER's behaviour under this test's
// direct control, which is what makes the Trailers-Only and early-cancel cases
// expressible at all.
var greeterDesc = grpcgo.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*any)(nil),
	Methods: []grpcgo.MethodDesc{
		{
			MethodName: "SayHello",
			Handler: func(srv any, ctx context.Context, dec func(any) error, _ grpcgo.UnaryServerInterceptor) (any, error) {
				in := new(helloworld.HelloRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				return srv.(*greeter).sayHello(ctx, in)
			},
		},
	},
	Streams: []grpcgo.StreamDesc{
		{
			StreamName: "LotsOfReplies",
			Handler: func(srv any, stream grpcgo.ServerStream) error {
				in := new(helloworld.HelloRequest)
				if err := stream.RecvMsg(in); err != nil {
					return err
				}
				return srv.(*greeter).lotsOfReplies(in, stream)
			},
			ServerStreams: true,
		},
		{
			StreamName:    "LotsOfGreetings",
			Handler:       func(srv any, stream grpcgo.ServerStream) error { return srv.(*greeter).lotsOfGreetings(stream) },
			ClientStreams: true,
		},
		{
			StreamName:    "BidiHello",
			Handler:       func(srv any, stream grpcgo.ServerStream) error { return srv.(*greeter).bidiHello(stream) },
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld/helloworld.proto",
}

// serve starts a grpc-go server on a loopback port and returns its address.
func serve(t *testing.T, impl *greeter) string {
	t.Helper()
	lis, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("listen: %v", err)
	}
	s := grpcgo.NewServer()
	s.RegisterService(&greeterDesc, impl)

	done := make(chan struct{})
	go func() {
		defer close(done)
		_ = s.Serve(lis)
	}()
	t.Cleanup(func() {
		s.Stop()
		<-done
	})
	return lis.Addr().String()
}

// dial opens a poseidon connection to addr in the clear.
//
// PlaintextDialer plus Scheme "http" is prior-knowledge h2c: the preface goes
// out with no TLS and no upgrade dance, which is what grpc.NewServer with no
// credentials expects.
func dial(t *testing.T, addr string) *poseidongrpc.ClientConn {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	cc, err := poseidongrpc.Dial(ctx, addr, poseidongrpc.Options{
		Scheme:    "http",
		Authority: "localhost",
		Conn:      conn.ConnOptions{Dialer: &conn.PlaintextDialer{}},
	})
	if err != nil {
		t.Fatalf("dial %s: %v", addr, err)
	}
	t.Cleanup(func() { _ = cc.Close() })
	return cc
}

// newClient returns the generated ergonomic face over a fresh connection.
func newClient(t *testing.T, impl *greeter) poseidon.GreeterClient {
	t.Helper()
	return poseidon.NewGreeterClient(pgrpc.NewClient(
		dial(t, serve(t, impl)), pgrpc.WithCodec(protocodec.Codec{})))
}

// newCaller returns the generated buffer-reusing face over a fresh connection.
func newCaller(t *testing.T, impl *greeter) *poseidon.GreeterCaller {
	t.Helper()
	return poseidon.NewGreeterCallerOn(dial(t, serve(t, impl)))
}

// testCtx bounds every test, so a hang is a failure rather than a stuck suite.
func testCtx(t *testing.T) context.Context {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	t.Cleanup(cancel)
	return ctx
}

// statusOf is the grpc-go side of a status, for asserting against what the
// server actually sent.
func statusOf(err error) (codes.Code, string) {
	st, _ := status.FromError(err)
	return st.Code(), st.Message()
}
