// Package pgrpc is the runtime that code generated by protoc-gen-go-poseidon
// calls into. It turns poseidon's byte-oriented gRPC transport into a typed
// one, and nothing else.
//
// # Why this is a separate module
//
// Three modules are in play, and the split is deliberate rather than tidy:
//
//	github.com/lodgvideon/poseidon-http-client              the transport
//	github.com/lodgvideon/protoc-gen-go-poseidon            the plugin binary
//	github.com/lodgvideon/protoc-gen-go-poseidon/pgrpc      this package
//
// poseidon's root module has four requirements and is meant to keep having
// four: it speaks gRPC as []byte precisely so that nothing forces protobuf on a
// caller who does not want it. Typed clients do need a codec, so the protobuf
// dependency lives here instead.
//
// The plugin binary is separated from this package for the mirror-image reason.
// Generated code imports pgrpc at run time; it must not drag in
// google.golang.org/protobuf/compiler/protogen, which only the generator needs.
// One module for both would put the whole compiler graph into every consumer's
// go.sum.
//
// # What it does not do
//
// It never wraps [grpc.Dial]. A generated client is constructed over a
// connection the caller already opened and owns, so connection options, TLS,
// keepalive and shutdown stay in poseidon's vocabulary rather than being
// re-invented in a second, worse one. See [Invoker].
//
// Name resolution, load balancing, retry policy and per-call authentication are
// out of scope here for the same reason they are out of scope in poseidon's
// grpc package: they belong above the transport.
//
// # Goroutine rules
//
// These are inherited from poseidon's grpc.Stream and are not negotiable at
// this layer, because breaking them corrupts a connection rather than merely
// failing a call:
//
//   - The send side and the receive side of one stream may run on two different
//     goroutines. That is what makes bidirectional streaming work.
//   - Each side on its own is single-goroutine. Two goroutines calling Recv on
//     the same stream is a data race, not a slow path.
//   - Trailers and the terminal status may only be read from the goroutine that
//     drove Recv, and only after Recv has reported the end of the stream.
//   - A stream must be closed unless it was read to completion, and Close must
//     not run while another goroutine is inside Recv. Cancel that goroutine's
//     context first.
//
// The stream types in this package check what they can check and report misuse
// as an error rather than letting it become a silent corruption; see Guard.
package pgrpc
